// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxs-xykcLt8-aA_MpZ-wD_ltfKkRVWqug',
    appId: '1:761766595131:web:1b1db40673b243479a2a1e',
    messagingSenderId: '761766595131',
    projectId: 'flashnews-abad5',
    authDomain: 'flashnews-abad5.firebaseapp.com',
    storageBucket: 'flashnews-abad5.appspot.com',
    measurementId: 'G-RX0BSER3WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfd6E6gJd-ec1H6BtJOGEYsCi0fRF4EV0',
    appId: '1:761766595131:android:60b08bbfbb86f3a49a2a1e',
    messagingSenderId: '761766595131',
    projectId: 'flashnews-abad5',
    storageBucket: 'flashnews-abad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Oiu9VlpDLKorNxFk_RDURdwZLl0afIQ',
    appId: '1:761766595131:ios:81e4f1239791b9429a2a1e',
    messagingSenderId: '761766595131',
    projectId: 'flashnews-abad5',
    storageBucket: 'flashnews-abad5.appspot.com',
    iosBundleId: 'com.example.flashnews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Oiu9VlpDLKorNxFk_RDURdwZLl0afIQ',
    appId: '1:761766595131:ios:81e4f1239791b9429a2a1e',
    messagingSenderId: '761766595131',
    projectId: 'flashnews-abad5',
    storageBucket: 'flashnews-abad5.appspot.com',
    iosBundleId: 'com.example.flashnews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxs-xykcLt8-aA_MpZ-wD_ltfKkRVWqug',
    appId: '1:761766595131:web:0d80f1fdbf2667099a2a1e',
    messagingSenderId: '761766595131',
    projectId: 'flashnews-abad5',
    authDomain: 'flashnews-abad5.firebaseapp.com',
    storageBucket: 'flashnews-abad5.appspot.com',
    measurementId: 'G-983D9R2XRW',
  );
}
